/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Klijent;
import domen.TipUsluge;
import domen.Usluga;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ninic
 */
public class DodajRezervacijuForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajRezervacijuForma
     */
    public DodajRezervacijuForma() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeRez = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxUsluga = new javax.swing.JComboBox<>();
        jButtonDodajStavku = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCenaUsluge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxTipUsluge = new javax.swing.JComboBox<>();
        jComboBoxVremePocetka = new javax.swing.JComboBox<>();
        jComboBoxVremeZavrsetka = new javax.swing.JComboBox<>();
        jButtonObrisiStavku = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxKlijent = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButtonDodajRezervaciju = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUkupnaCena = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePopusti = new javax.swing.JTable();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonAzuriraj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jLabelDolazak = new javax.swing.JLabel();
        jComboBoxDolazak = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavke rezervacije", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jTableStavkeRez.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeRez);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dodaj novu stavku", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Vreme pocetka");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Vreme zavrsetka");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Usluga");

        jButtonDodajStavku.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonDodajStavku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/resources/add.png"))); // NOI18N
        jButtonDodajStavku.setText("Dodaj stavku");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Cena usluge");

        jTextFieldCenaUsluge.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Tip usluge");

        jComboBoxVremePocetka.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jComboBoxVremeZavrsetka.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDodajStavku)
                    .addComponent(jTextFieldCenaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxTipUsluge, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxUsluga, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxVremeZavrsetka, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE)
                        .addComponent(jComboBoxVremePocetka, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxTipUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxVremePocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCenaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDodajStavku))
        );

        jButtonObrisiStavku.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonObrisiStavku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/resources/delete.png"))); // NOI18N
        jButtonObrisiStavku.setText("Obrisi oznacenu stavku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButtonObrisiStavku))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonObrisiStavku))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Datum (dd.mm.yyyy)");

        jTextFieldDatum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldDatum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Klijent");

        jComboBoxKlijent.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Podaci o rezervaciji");

        jButtonDodajRezervaciju.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonDodajRezervaciju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/resources/add.png"))); // NOI18N
        jButtonDodajRezervaciju.setText("Sacuvaj rezervaciju");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Cena (ukupno) ");

        jTextFieldUkupnaCena.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldUkupnaCena.setText("0");
        jTextFieldUkupnaCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUkupnaCenaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Popusti klijenta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jTablePopusti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePopusti);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabelId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelId.setText("Id");

        jButtonAzuriraj.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonAzuriraj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/resources/update.png"))); // NOI18N
        jButtonAzuriraj.setText("Azuriraj rezervaciju");

        jButtonObrisi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/resources/delete.png"))); // NOI18N
        jButtonObrisi.setText("Obrisi rezervaciju");

        jLabelDolazak.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelDolazak.setText("Dolazak");

        jComboBoxDolazak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Da", "Ne" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDodajRezervaciju)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDolazak, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxKlijent, javax.swing.GroupLayout.Alignment.TRAILING, 0, 169, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldId)
                                    .addComponent(jComboBoxDolazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButtonAzuriraj)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDolazak)
                            .addComponent(jComboBoxDolazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButtonDodajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAzuriraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatumActionPerformed

    private void jTextFieldUkupnaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUkupnaCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUkupnaCenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getjButtonDodajStavku() {
        return jButtonDodajStavku;
    }

    public void setjButtonDodajStavku(JButton jButtonDodajStavku) {
        this.jButtonDodajStavku = jButtonDodajStavku;
    }

    public JButton getjButtonObrisiStavku() {
        return jButtonObrisiStavku;
    }

    public void setjButtonObrisiStavku(JButton jButtonObrisiStavku) {
        this.jButtonObrisiStavku = jButtonObrisiStavku;
    }

    public JComboBox<Klijent> getjComboBoxKlijent() {
        return jComboBoxKlijent;
    }

    public void setjComboBoxKlijent(JComboBox<Klijent> jComboBoxKlijent) {
        this.jComboBoxKlijent = jComboBoxKlijent;
    }

    public JComboBox<LocalTime> getjComboBoxVremePocetka() {
        return jComboBoxVremePocetka;
    }

    public JComboBox<String> getjComboBoxDolazak() {
        return jComboBoxDolazak;
    }

    public JLabel getjLabelDolazak() {
        return jLabelDolazak;
    }

    public void setjLabelDolazak(JLabel jLabelDolazak) {
        this.jLabelDolazak = jLabelDolazak;
    }

    public void setjComboBoxDolazak(JComboBox<String> jComboBoxDolazak) {
        this.jComboBoxDolazak = jComboBoxDolazak;
    }

    public void setjComboBoxVremePocetka(JComboBox<LocalTime> jComboBoxVremePocetka) {
        this.jComboBoxVremePocetka = jComboBoxVremePocetka;
    }

    public JComboBox<LocalTime> getjComboBoxVremeZavrsetka() {
        return jComboBoxVremeZavrsetka;
    }

    public void setjComboBoxVremeZavrsetka(JComboBox<LocalTime> jComboBoxVremeZavrsetka) {
        this.jComboBoxVremeZavrsetka = jComboBoxVremeZavrsetka;
    }

    public JComboBox<Usluga> getjComboBoxUsluga() {
        return jComboBoxUsluga;
    }

    public void setjComboBoxUsluga(JComboBox<Usluga> jComboBoxUsluga) {
        this.jComboBoxUsluga = jComboBoxUsluga;
    }

    public JTextField getjTextFieldCenaUsluge() {
        return jTextFieldCenaUsluge;
    }

    public void setjTextFieldCenaUsluge(JTextField jTextFieldCenaUsluge) {
        this.jTextFieldCenaUsluge = jTextFieldCenaUsluge;
    }

    public JTextField getjTextFieldDatum() {
        return jTextFieldDatum;
    }

    public void setjTextFieldDatum(JTextField jTextFieldDatum) {
        this.jTextFieldDatum = jTextFieldDatum;
    }

    public JLabel getjLabelId() {
        return jLabelId;
    }

    public void setjLabelId(JLabel jLabelId) {
        this.jLabelId = jLabelId;
    }

    public JTextField getjTextFieldUkupnaCena() {
        return jTextFieldUkupnaCena;
    }

    public JTable getjTableStavkeRez() {
        return jTableStavkeRez;
    }

    public void setjTableStavkeRez(JTable jTableStavkeRez) {
        this.jTableStavkeRez = jTableStavkeRez;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTextFieldUkupnaCena(JTextField jTextFieldUkupnaCena) {
        this.jTextFieldUkupnaCena = jTextFieldUkupnaCena;
    }

    public JComboBox<TipUsluge> getjComboBoxTipUsluge() {
        return jComboBoxTipUsluge;
    }

    public void setjComboBoxTipUsluge(JComboBox<TipUsluge> jComboBoxTipUsluge) {
        this.jComboBoxTipUsluge = jComboBoxTipUsluge;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodajRezervaciju;
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JComboBox<String> jComboBoxDolazak;
    private javax.swing.JComboBox<Klijent> jComboBoxKlijent;
    private javax.swing.JComboBox<TipUsluge> jComboBoxTipUsluge;
    private javax.swing.JComboBox<Usluga> jComboBoxUsluga;
    private javax.swing.JComboBox<LocalTime> jComboBoxVremePocetka;
    private javax.swing.JComboBox<LocalTime> jComboBoxVremeZavrsetka;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDolazak;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePopusti;
    private javax.swing.JTable jTableStavkeRez;
    private javax.swing.JTextField jTextFieldCenaUsluge;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldUkupnaCena;
    // End of variables declaration//GEN-END:variables

    public void DatumAddActionListener(ActionListener actionListener) {

        jTextFieldDatum.addActionListener(actionListener);
    }

    public void dodajStavkuAddActionListener(ActionListener actionListener) {

        jButtonDodajStavku.addActionListener(actionListener);
    }

    public void obrisiStavkuAddActionListener(ActionListener actionListener) {

        jButtonObrisiStavku.addActionListener(actionListener);
    }

    public void dodajRezAddActionListener(ActionListener actionListener) {

        jButtonDodajRezervaciju.addActionListener(actionListener);
    }

    public void ComboBoxActionListener(ActionListener actionListener) {

        jComboBoxUsluga.addActionListener(actionListener);
        jComboBoxVremePocetka.addActionListener(actionListener);
    }

    public void ComboBoxUslugaActionListener(ActionListener actionListener) {

        jComboBoxUsluga.addActionListener(actionListener);
    }

    public void ComboBoxKlijentActionListener(ActionListener actionListener) {

        jComboBoxKlijent.addActionListener(actionListener);

    }

    public void ComboBoxTipUslugeActionListener(ActionListener actionListener) {

        jComboBoxTipUsluge.addActionListener(actionListener);

    }

    public void ObrisiRezAddActionListener(ActionListener actionListener) {

        jButtonObrisi.addActionListener(actionListener);
    }

    public void AzurirajRezAddActionListener(ActionListener actionListener) {

        jButtonAzuriraj.addActionListener(actionListener);
    }

    public JButton getjButtonDodajRezervaciju() {
        return jButtonDodajRezervaciju;
    }

    public void setjButtonDodajRezervaciju(JButton jButtonDodajRezervaciju) {
        this.jButtonDodajRezervaciju = jButtonDodajRezervaciju;
    }

    public JTable getjTablePopusti() {
        return jTablePopusti;
    }

    public void setjTablePopusti(JTable jTablePopusti) {
        this.jTablePopusti = jTablePopusti;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public void setjTextFieldId(JTextField jTextFieldId) {
        this.jTextFieldId = jTextFieldId;
    }

    public JButton getjButtonAzuriraj() {
        return jButtonAzuriraj;
    }

    public void setjButtonAzuriraj(JButton jButtonAzuriraj) {
        this.jButtonAzuriraj = jButtonAzuriraj;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public void setjButtonObrisi(JButton jButtonObrisi) {
        this.jButtonObrisi = jButtonObrisi;
    }

}
